---
title: "waffle"
format: html
---

```{r}
require(waffle)
require(tidyverse)
```

```{r}
iron(waffle(parts = c("Pemba" = 65, "Zanzibar" = 25, "Mafia" = 10, "Mtwara" =20), rows = 5, flip = FALSE, reverse = FALSE, legend_pos = "top"))
```

```{r}
savings <- c(
  `Mortgage\n($84,911)` = 84911, `Auto and\ntuition loans\n($14,414)` = 14414,
  `Home equity loans\n($10,062)` = 10062, `Credit Cards\n($8,565)` = 8565
)

waffle(
  savings / 392, rows = 7, size = 0.5, legend_pos = "bottom",
  colors = c("#c7d4b6", "#a3aabd", "#a0d0de", "#97b5cf")
)
```

```{r}
professional <- c(`Male` = 44, `Female (56%)` = 56)

waffle(
  professional, rows = 4, size = 0.5,
  colors = c("darkorange", "cyan4")
)
```

```{r}
samaki = c("Pelagics" = 200, "Octopus" = 400, "Reef" = 150)
wavuvi = c("boat" = 1500, "Dhow" = 850, "Ngalawa" = 4800)

samaki = waffle(samaki/7, rows = 5)
vyombo = waffle(wavuvi/70, rows = 5)

iron(samaki, vyombo)
```

```{r}
library(hrbrthemes)
library(waffle)
library(tidyverse)

xdf = tibble(
  parts = factor(rep(month.abb[1:3], 3), levels=month.abb[1:3]),
  seasons = rep(c("Southeast", "Northeast", "Inter"), times = 3),
  values = c(10, 20, 30, 6, 14, 40, 30, 20, 10),
  fct = c(rep("Zone A", 3), rep("Zone B", 3), rep("Zone C", 3)))


ggplot(xdf, aes(fill=seasons, values=values)) +
  geom_waffle(color = "white", size=1.125, n_rows = 6) +
  facet_wrap(~fct, ncol=3) +
  scale_x_discrete(expand=c(0,0)) +
  scale_y_discrete(expand=c(0,0)) +
  ggthemes::scale_fill_tableau(name=NULL) +
  coord_equal() +
  labs(
    title = "Faceted Waffle Geoms"
  ) +
  # theme_ipsum_rc(grid="") +
  theme_enhance_waffle()+
  theme(strip.background = element_blank())

```


